;;-----------------------------LICENSE NOTICE-----------------------------------------------------
;;  This file is part of Amstrad CPC videogame "Agent 006"
;;  Copyright (C) 2017 APLSoft / Adrian Frances Lillo / Pablo Lopez Iborra / Luis Gonzalez Aracil
;;  Copyright (C) 2015-2016 ronaldo / Fremos / Cheesetea / ByteRealms (@FranGallegoBR)
;;
;;  This program is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU Lesser General Public License as published by
;;  the Free Software Foundation, either version 3 of the License, or
;;  (at your option) any later version.
;;
;;  This program is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;  GNU Lesser General Public License for more details.
;;
;;  You should have received a copy of the GNU Lesser General Public License
;;  along with this program.  If not, see <http://www.gnu.org/licenses/>.
;;-----------------------------LICENSE NOTICE-----------------------------------------------------

;;;
;;; File generated by cpct_aks2c CPCtelera script
;;; Souce file of this conversion: assets/music/Shot.aks
;;; Generation time: lu., 23 de oct. de 2017 20:48:32
;;;

;;; Set absolute memory addressing
.area __SFX_shot (ABS)
.org 0x0500

;;; Music data start (87 bytes)
;;;
_SFX_shot::
.db 0x41, 0x54, 0x31, 0x30, 0x01, 0x40, 0x42, 0x0f, 0x02, 0x06, 0x2d, 0x00, 0x10, 0x05, 0x19, 0x05
.db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0d, 0x12, 0x05, 0x01, 0x00, 0x3e, 0x3f, 0x3a, 0x3b, 0x36
.db 0x39, 0x32, 0x37, 0x2e, 0x34, 0x2a, 0x31, 0x26, 0x30, 0x22, 0x2e, 0x1e, 0x2d, 0x1a, 0x2a, 0x16
.db 0x27, 0x12, 0x26, 0x0c, 0x08, 0x04, 0x0d, 0x12, 0x05, 0x01, 0x00, 0x00, 0x00, 0x49, 0x05, 0x00
.db 0x4a, 0x05, 0x4f, 0x05, 0x53, 0x05, 0x01, 0x3f, 0x05, 0x00, 0xa2, 0xe0, 0x00, 0x00, 0x01, 0x42
.db 0x80, 0x00, 0x00, 0x42, 0x80, 0x00, 0x00